[project]
name = "jellyfin-helpers"
version = "0.0.1"
description = "Helper scrips to deal with media libraries for e.g. Jellyfin media server."
authors = [{ name = "Aurorian Clouds" }]
requires-python = ">=3.11,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
]

[tool.poetry.dependencies]
pandas = ">=3.0.5,<4"
pydantic = "^2.13.4"
hydra-core = "^1.3.2"
pandera = "^0.32.1"
utilities = {path = "../utilities/", develop = true}
joblib = "^1.3.2"
numpy = "^2.4.6"

[dependency-groups]
dev = [
    "pytest>=9.0.0,<10",
    "pytest-cov>=4.1.0,<5",
    "freezegun>=1.1,<2",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "gsheets: marks tests using gsheets",
    "jellyfin: marks tests using jellyfin",
    "todoist: marks tests using todoist, which requires periodically updating API key",
    "youtube: marks tests using youtube",
]
