format_ingredient:
  # mininum length for line to be considered
  min_line_length: 3
  # formats for referenced recipe
  referenced_recipe_format:
    unit_with_ingredient: '([\w+\-\s\%\.'']+)'
    prefix_pattern: [with_decimal_quantity, with_integer, with_none]
    with_none:
      pattern: '^#\s'
      group: ['item']
    with_integer:
      pattern: '^#\s(\d+)\s'
      group: ['quantity', 'item']
    with_decimal_quantity:
      pattern: '^#\s(\d+\.\d*)\s'
      group: ['quantity', 'item']
  ingredient_line_format:
    unit_with_ingredient: '([\w+\-\s\%\.'']+)'
    prefix_pattern: [with_decimal_quantity, with_whole_and_fractional_quantity,
                     with_fractional_quantity, with_integer, with_none]
    with_none:
      pattern: '^'
      group: ['item']
    with_integer:
      pattern: '^(\d+)\s'
      group: ['quantity', 'item']
    with_fractional_quantity:
      pattern: '^(\d\/\d)\s'
      group: ['fraction', 'item']
    with_whole_and_fractional_quantity:
      pattern: '^(\d+)\s(\d\/\d)\s'
      group: ['quantity', 'fraction', 'item']
    with_decimal_quantity:
      pattern: '^(\d+\.\d*)\s'
      group: ['quantity', 'item']
