get_ingredient_field:
  errors:
    recipe_not_found: log
    ingredient_line_parsing_error: log
    no_ingredient_found_in_line: log
    pantry_ingredient_not_known: log
    ingredient_marked_as_bad: log
