FROM python:3.9
SHELL ["/bin/bash", "-c"]
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
RUN pip install 'poetry==1.1.12'
WORKDIR /code
COPY poetry.lock poetry.toml pyproject.toml /code/
RUN poetry config virtualenvs.create false
RUN poetry install