name: Setup Python environment
description: "Setup Python Environment"
inputs:
  poetry-dir:
    required: true
    description: "Poetry directory"
  gsheets-service-token:
    required: true
    description: "Token for Gsheets service"
  todoist-token:
    required: true
    description: "Token for Todoist service"
runs:
  using: "composite"
  steps:
    - name: Setup Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.2.2
    - name: Install dependencies
      shell: bash
      working-directory: ./${{ inputs.poetry-dir }}
      run: poetry install
    - name: Setup token directory
      shell: bash
      run: |
        TOKEN_DIR=./tokens
        mkdir $TOKEN_DIR
        GSHEETS_TOKEN="${TOKEN_DIR}/google_client_key.json"
        TODOIST_TOKEN="${TOKEN_DIR}/todoist_token.txt"
        echo ${{ inputs.gsheets-service-token }} > $GSHEETS_TOKEN
        echo ${{ inputs.todoist-token }} > $TODOIST_TOKEN
