name: Set up Python environment
description: Set up Python, Poetry, project dependencies, and service tokens
inputs:
  poetry-dir:
    required: true
    description: "Poetry directory"
  gsheets-service-token:
    required: true
    description: "Token for Gsheets service"
  todoist-token:
    required: true
    description: "Token for Todoist service"
runs:
  using: "composite"
  steps:
    - name: Set up Python environment
      uses: ./.github/actions/poetry-setup
      with:
        poetry-dir: ${{ inputs.poetry-dir }}
    - name: Set up token directory
      shell: bash
      run: |
        TOKEN_DIR=./tokens
        mkdir -p "$TOKEN_DIR"
        GSHEETS_TOKEN="${TOKEN_DIR}/google_client_key.json"
        TODOIST_TOKEN="${TOKEN_DIR}/todoist_token.txt"
        printf '%s' "${INPUTS_GSHEETS_SERVICE_TOKEN:1:${#INPUTS_GSHEETS_SERVICE_TOKEN}-2}" > "$GSHEETS_TOKEN"
        printf '%s' "$INPUTS_TODOIST_TOKEN" > "$TODOIST_TOKEN"
      env:
        INPUTS_GSHEETS_SERVICE_TOKEN: ${{ inputs.gsheets-service-token }}
        INPUTS_TODOIST_TOKEN: ${{ inputs.todoist-token }}
