defaults:
  - _self_
  - pantry_list
  - recipe_book
  - rtk
  - formatter/format_ingredient
  - messaging/gsheets_api
  - messaging/todoist_api

menu:
  input_method: fixed
  output_method: local
  fixed:
    file_prefix: menu-
    menu_number:
  local:
    file_path: ../menu/menu-tmp.csv
  run_mode:
    with_inspect_unrated_recipe: true
    with_todoist: true
  todoist:
    project_name: Menu
    remove_existing_task: true
