defaults:
  - pantry_list
  - recipe_book
  - rtk
  - formatter/format_ingredient
  - menu/create_menu
  - messaging/gmail_api
  - messaging/gsheets_api
  - messaging/todoist_api
  - _self_

menu:
  create_menu:
    input_method: fixed
  run_mode:
    with_gmail: true
    with_todoist: true
  todoist:
    project_name: Menu
    remove_existing_task: true
