defaults:
  - menu/create_menu
  - pantry_list
  - recipe_book
  - rtk
  - date/get_due_date
  - formatter/format_ingredient
  - formatter/get_ingredient_field
  - api/gsheets_api
  - api/todoist_api
  - _self_

formatter:
  get_ingredient_field:
    errors:
      recipe_not_found: log
      ingredient_line_parsing_error: log
      no_ingredient_found_in_line: log
      pantry_ingredient_not_known: log
      ingredient_marked_as_bad: log

menu:
  create_menu:
    input_method: final
    errors:
      recipe_not_found: log
      pantry_ingredient_not_known: log
      ingredient_marked_as_bad: log

grocery_list:
  shopping:
    primary_day: Friday
    secondary_day: Monday
    secondary_group: [fresh herbs, lettuce]
  preparation:
    project_name: Menu
    task_priority: 3
  bean_prep:
    prep_day: 1
    prep_meal: lunch
  todoist:
    project_name: Groceries
    remove_existing_task: true
    remove_existing_prep_task: false
    skip_group: [garden]
  run_mode:
    check_referenced_recipe: true
    with_todoist: false
    # remove existing entries in todoist (and nothing else)
    only_clean_todoist_mode: false
  ingredient_replacement:
    can_to_dried_bean:
      is_active: true
      bean_list: [black beans, butter beans, chickpeas, kidney beans,
                  white beans, pinto beans]
      # conversion from can to dried grams
      g_per_can: 105
      # bump quantity of what to prepare for freezing
      number_can_to_freeze: 1
  default_store: 'grocery store'
  food_group_to_aisle_map:
    baking: Sweet carolina
    beans: Bulk
    beverages: Juices and beverages
    canned: Sauces cans and oils
    dairy products: Dairy force
    egg: Bulk
    fats and oils: Sauces cans and oils
    fish: Dead animal society
    fresh herbs: Farmland pride
    frozen goods: Frozen 3
    fruits: Farmland pride
    grains: Bulk
    juices: Juices and beverages
    legumes: Bulk
    lettuce: Farmland pride
    meats: Dead animal society
    nuts and seeds: Bulk
    pasta: GF park
    prepared: GF park
    sauces: Sauces cans and oils
    spices and herbs: Spices and herbs
    vegetables: Farmland pride
  store_to_specialty_list: [unknown, America, Food Oase,
                            Kaufland, Lillehus, Waldstadt]
