defaults:
  - pantry_list
  - random
  - recipe_book
  - rtk
  - date/get_due_date
  - formatter/format_ingredient
  - menu/create_menu
  - menu/record_menu_history
  - api/gsheets_api
  - api/todoist_api
  - _self_

menu:
  create_menu:
    input_method: fixed
    errors:
      recipe_not_found: log
      random_recipe_selection_failed: log
      recipe_total_time_undefined: log
      recipe_in_recent_menu_history: log
      pantry_ingredient_not_known: log
      ingredient_marked_as_bad: log
      menu_quality_check: log
      menu_future_error: log
    todoist:
      remove_existing_task: true
