defaults:
  - pantry_list
  - recipe_book
  - rtk
  - formatter/format_ingredient
  - menu/create_menu
  - menu/record_menu_history
  - messaging/gmail_api
  - messaging/gsheets_api
  - messaging/todoist_api
  - _self_

menu:
  anchor_day: Sunday
  menu_history_days: 30
  create_menu:
    input_method: fixed
    todoist:
      remove_existing_task: true
  run_mode:
    with_gmail: true
    with_todoist: true
