recipe_book:
  path: ./Dropbox/SharedApps/RecetteTek
  file_pattern: recipes*.json
  # selects recipe with highest rating if name duplicated
  deduplicate: true
  fuzzy_match:
    limit_number_results: 1
    warn: true
    min_thresh_ok_match: 75
    min_thresh_to_accept: 90
  random_select:
    min_thresh_error: 0
    min_thresh_warning: 10
    default_rating: 3
