# Generated by Django 3.2.12 on 2022-03-29 11:04

import datetime

import django.db.models.deletion
import house_keeper.cleaner.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, unique=True)),
                ("can_shift", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (5, "unessential"),
                            (4, "low"),
                            (3, "normal"),
                            (2, "high"),
                            (1, "critical"),
                        ],
                        default=house_keeper.cleaner.models.Priority["low"],
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("duration_active", models.DurationField()),
                (
                    "duration_passive",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("frequency", models.DurationField()),
                ("date_last_done", models.DateField()),
                (
                    "category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="cleaner.category",
                    ),
                ),
            ],
        ),
    ]
