bank_name: "Sparkasse"
date_format: "DD.MM.YY"
skip_rows: 0
delimiter: ";"

column_mappings:
  Date:
    source_columns: ["Buchungstag"]
    parser: "date"
  Category:
    source_columns: ["Verwendungszweck", "Beguenstigter/Zahlungspflichtiger"]
    parser: "pattern_category"
    patterns:
      rewe|edeka|alnatura|aldi|penny|lidl|kaufland|netto|isabella|orient master: groceries
      "dm|rossmann|müller": "household"
      "cafe|restaurant|imbiss|bäckerei|takeaway": "takeout"
      "apotheke": "medical"
      "strom|gas|wasser|elektrizität|yello": "utilities"
      "miete|nebenkosten|rent": "rent"
      "spotify|netflix|disney|amazon prime video": "fun"
      "etsy": "household"
      "db vertrieb": "transit"
      "agila": "insurance"
      "vet concept": "pet groceries"
      "mae.studio": "sports"
    default: "household"
  Payment:
    parser: "literal"
    value: "ariel personal"
  Payer:
    parser: "literal"
    value: "ariel"
  Benefiter:
    parser: "literal"
    value: "house-ours"
  Amount:
    source_columns: ["Betrag"]
    parser: "amount"
    positive_is: "debit"
    decimal_separator: ","
  "To-update":
    parser: "literal"
    value: ""
  Description:
    source_columns: ["Verwendungszweck", "Beguenstigter/Zahlungspflichtiger"]
    parser: "string"
