defaults:
  - gsheets_api
  - jellyfin_api
  - todoist_api
  - _self_


plan_workouts:
  debug: True
  clean_up: False
  todoist:
    project: Active tasks
    section: ariel_workouts
    task_priority: 2
    task_priority_optional: 1
    task_label: workout-app
  gsheets:
    workbook: ariel_workout
    worksheet:
      weekly: weekly-bike
      sleep: basic-sleep
      sets: basic-set
      plan: plan
  jellyfin:
    playlist_1: ariel-week-1
    playlist_2: ariel-week-2
    playlist_3: ariel-week-3
    playlist_4: ariel-week-4
