name: sous_chef_py39
channels:
  - defaults
dependencies:
  - python=3.9.1
  - pytest=6.2.1
  - pandas=1.1.5
  - pyyaml=5.3.1
  - numpy=1.19.2
  - scipy=1.6.1
  - pip=20.3.3
  - pip:
      - google-api-python-client==1.12.8
      - google-auth-httplib2==0.0.4
      - google-auth-oauthlib==0.4.2
      - black==21.5b0
      - isort==5.8.0
      - json2html==1.3.0
      - pint==0.16.1
      - pre-commit==2.12.1
      - quantulum3==0.7.6
      - todoist-python==8.1.3
      - feather-format==0.4.1
      - fuzzywuzzy==0.18.0
      - python-Levenshtein==0.12.2
