name: sous_chef_py39
channels:
  - defaults
dependencies:
  - python=3.9.1
  - pytest=6.2.1
  - pandas=1.1.5
  - pyyaml=5.3.1
  - numpy=1.19.2
  - pip=20.3.3
  - pip:
      - google-api-python-client==1.12.8
      - google-auth-httplib2==0.0.4
      - google-auth-oauthlib==0.4.2
      - json2html==1.3.0
      - pint==0.16.1
      - quantulum3==0.7.6
      - todoist==0.0.1