create_menu:
  input_method:
  output_method: temp
  ingredient:
    default_cook_minutes: 20
  prep_separate:
    min_inactive_minutes: 20
  quality_check:
    recipe_rating_min: 3.0
    weekend:
      recipe_unrated_allowed: true
      cook_active_minutes_max: 40
    workday:
      recipe_unrated_allowed: true
      cook_active_minutes_max: 30
  max_number_of_unrated_recipes: 3
  menu_history_recent_days: 30
  errors: # raise, log, or skip
    recipe_not_found: raise
    random_recipe_selection_failed: raise
    recipe_total_time_undefined: raise
    recipe_in_recent_menu_history: raise
    pantry_ingredient_not_known: raise
    ingredient_marked_as_bad: raise
    menu_quality_check: raise
    menu_future_error: raise
  todoist:
    project_name: Menu
    remove_existing_task: false
    task_priority: 3
  fixed:
    workbook: fixed_menus
    basic_number: 0
    menu_number:
    # if 0 is used as a basic menu, then change this to 1
    min_menu_number: 1
    # skips for random selections; gives error for hard-coded recipes
    # will include even ignored recipes atm
    already_in_future_menus:
      active: true
      num_weeks: 4
    default_time: dinner
  final_menu:
    workbook: menu-tmp
    worksheet: menu-tmp
  run_mode:
    with_inspect_unrated_recipe: true
