create_menu:
  input_method:
  output_method: temp
  ingredient:
    default_cook_minutes: 20
  prep_separate:
    default_time: dinner
    min_inactive_minutes: 20
  quality_check:
    recipe_rating_min: 3.0
    workday:
      recipe_unrated_allowed: true
      cook_active_minutes_max: 30
  max_number_of_unrated_recipes: 2
  menu_history_recent_days: 30
  errors: # raise, log, or skip
    recipe_not_found: raise
    random_recipe_selection_failed: raise
    recipe_total_time_undefined: raise
    recipe_in_recent_menu_history: raise
    pantry_ingredient_not_known: raise
    ingredient_marked_as_bad: raise
    menu_quality_check: raise
  todoist:
    project_name: Menu
    remove_existing_task: false
    task_priority: 3
  fixed:
    basic: menu-basic
    cook_days:
      weekend_1: Saturday
      weekend_2: Sunday
      work_day_0: Monday
      work_day_1: Tuesday
      work_day_2: Friday
      work_day_3: Wednesday
    file_prefix: menu-
    menu_number:
  final_menu:
    workbook: menu-tmp
    worksheet: menu-tmp
  run_mode:
    with_inspect_unrated_recipe: true
