create_menu:
  input_method:
  output_method: local
  anchor_day: Sunday
  todoist:
    project_name: Menu
    remove_existing_task: False
  fixed:
    basic: menu-basic
    cook_days:
      weekend_1: Saturday
      weekend_2: Sunday
      work_day_1: Tuesday
      work_day_2: Friday
      work_day_3: Wednesday
    file_prefix: menu-
    menu_number:
  local:
    file_path: ../menu/menu-tmp.csv
  run_mode:
    with_inspect_unrated_recipe: true
