name: CI
on: [push, pull_request]
jobs:
  ci:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.12]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Test with pytest
        run: poetry run pytest ./sous_chef/tests/unit_tests
