name: coverage
on: [pull_request]
jobs:
  coverage:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.12]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install
      - name: Get coverage
        run: |
          poetry run coverage run  --rcfile .coveragerc. -m pytest \
          sous_chef/tests/unit_tests
      - name: Create coverage XML
        run: poetry run coverage xml
      - name: Output coverage report
        run: poetry run coverage report
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: false
