name: merge to main
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-main
  cancel-in-progress: true

jobs:
  call-utilities:
    uses: ./.github/workflows/test_utilities.yml
    secrets: inherit
  call-jellyfin-helpers:
    uses: ./.github/workflows/test_jellyfin_helpers.yml
    secrets: inherit
  call-sous-chef-tests:
    uses: ./.github/workflows/test_sous_chef.yml
    secrets: inherit
