name: pull request
on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}-pr
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-zizmor:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Python environment
        uses: ./.github/actions/poetry-setup
        with:
          poetry-dir: .
      - name: Run Zizmor
        run: poetry run zizmor .github/workflows
  call-utilities:
    uses: ./.github/workflows/test_utilities.yml
    permissions:
      contents: read
    secrets:
      GSHEETS_SERVICE_TOKEN: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
      TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  call-jellyfin-helpers:
    uses: ./.github/workflows/test_jellyfin_helpers.yml
    permissions:
      contents: read
    secrets:
      GSHEETS_SERVICE_TOKEN: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
      TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  call-sous-chef-tests:
    uses: ./.github/workflows/test_sous_chef.yml
    permissions:
      contents: read
    secrets:
      GSHEETS_SERVICE_TOKEN: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
      TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  call-banking-helpers-tests:
    uses: ./.github/workflows/test_banking_helpers.yml
    permissions:
      contents: read
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  allow-merge:
    name: Allow Merge
    if: ${{ !cancelled() }}
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    needs:
      - run-zizmor
      - call-utilities
      - call-jellyfin-helpers
      - call-sous-chef-tests
      - call-banking-helpers-tests
    steps:
      - name: Branch Protection - failure if any test workflow failed or was cancelled
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        env:
          NEEDS_JSON: ${{ toJSON(needs) }}
        run: |
          echo "$NEEDS_JSON"
          exit 1
      - name: Branch protection
        run: echo "All required test workflows passed or were skipped. Merge allowed."
