name: pytest
on: [push, pull_request]
jobs:
  pytest:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.12]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: ./.github/actions/python-setup
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}
          address-book: ${{ secrets.ADDRESS_BOOK }}
          gmail-auth-token: ${{ secrets.GMAIL_AUTH_TOKEN }}
          gmail-client-key: ${{ secrets.GMAIL_CLIENT_KEY}}
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
      - name: Run unit tests
        run: poetry run pytest ./sous_chef/tests/unit_tests
      - name: Run integration tests
        run: poetry run pytest ./sous_chef/tests/integration_tests
