name: utilities tests
on:
  workflow_call:
    secrets:
      GSHEETS_SERVICE_TOKEN:
        required: true
      TODOIST_TOKEN:
        required: true
      SONAR_TOKEN_UTILITIES:
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-utilities
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Check if relevant files were changed
        id: filter
        uses: ./.github/actions/check-file-changes
        with:
          paths: |
            utilities/
            .github/workflows/test_utilities.yml
  pytest:
    needs: changes
    if: needs.changes.outputs.relevant == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up Python environment
        uses: ./.github/actions/poetry-setup-with-tokens
        with:
          poetry-dir: utilities
          poetry-lock-path: utilities/poetry.lock
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
      - name: Run tests
        working-directory: ./utilities
        run: poetry run pytest --cov=utilities --cov-report=xml:utilities_tests.xml ./tests/
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        with:
          projectBaseDir: ./utilities
          args: >-
            -Dsonar.projectKey=aurorianclouds.utilities
            -Dsonar.organization=aurorianclouds
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=utilities
            -Dsonar.tests=tests
            -Dsonar.python.version=3.11,3.12,3.13,3.14
            -Dsonar.python.coverage.reportPaths=utilities_tests.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_UTILITIES }}
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: cov_utilities
          path: ./utilities/*.xml
          retention-days: 5
