name: pytest
on: [push]
jobs:
  pytest:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.2.2]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment for sous-chef
        uses: ./.github/actions/sous-chef-setup
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}
          address-book: ${{ secrets.ADDRESS_BOOK }}
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
      - name: Run unit tests
        working-directory: ./sous-chef
        run: poetry run pytest ./tests/unit_tests
      - name: Run integration tests
        working-directory: ./sous-chef
        run: |
          poetry run pytest ./tests/integration_tests \
          -k "not todoist and not gmail and not dropbox"
