name: banking-helpers tests
on:
  workflow_call:
    secrets:
      SONAR_TOKEN_BANKING_HELPERS:
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-banking-helpers
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Check if relevant files were changed
        id: filter
        uses: ./.github/actions/check-file-changes
        with:
          paths: |
            banking-helpers/
            .github/workflows/test_banking_helpers.yml
  pytest:
    needs: changes
    if: needs.changes.outputs.relevant == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python environment
        uses: ./.github/actions/poetry-setup
        with:
          poetry-dir: banking-helpers
          poetry-lock-path: banking-helpers/poetry.lock
      - name: Run unit tests
        working-directory: ./banking-helpers
        run: poetry run pytest --cov=banking_helpers --cov-report=xml:banking_helpers_unit_tests.xml ./tests/unit
      - name: Run integration tests
        working-directory: ./banking-helpers
        run: poetry run pytest --cov=banking_helpers --cov-report=xml:banking_helpers_integration_tests.xml ./tests/integration
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@7006c4492b2e0ee0f816d36501671557c97f5995 # v8.1.0
        with:
          projectBaseDir: ./banking-helpers
          args: >-
            -Dsonar.projectKey=aurorianclouds.banking-helpers
            -Dsonar.organization=aurorianclouds
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=banking_helpers
            -Dsonar.tests=tests
            -Dsonar.python.version=3.11,3.12,3.13,3.14
            -Dsonar.python.coverage.reportPaths=banking_helpers_unit_tests.xml,banking_helpers_integration_tests.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BANKING_HELPERS }}
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: cov_banking_helpers
          path: ./banking-helpers/*.xml
          retention-days: 5
