name: sous-chef tests
on:
  push:
    paths:
      - sous-chef/**
      - .github/workflows/test_sous_chef.yml

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: ./.github/actions/poetry-setup-with-tokens
        with:
          poetry-dir: sous-chef
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
      - name: Run unit tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_unit_tests.xml ./tests/unit_tests
      - name: Run integration tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_integration_tests.xml -k "not dropbox and not openfoodfacts" ./tests/integration_tests
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: false
