name: sous-chef tests
on:
  push:
    paths:
      - sous-chef/**
      - .github/workflows/test_sous_chef.yml
      - utilities/utilities/** # since dependent on without version atm
    branches-ignore:
      - main
  workflow_call:
    secrets:
      GSHEETS_SERVICE_TOKEN:
        required: true
      TODOIST_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}-sous-chef
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: ./.github/actions/poetry-setup-with-tokens
        with:
          poetry-dir: sous-chef
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
      - name: Run unit tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_unit_tests.xml ./tests/unit_tests
      - name: Run integration tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_integration_tests.xml -k "not dropbox and not openfoodfacts" ./tests/integration_tests
      - name: Upload coverage to Codecov
        if: github.ref != 'refs/heads/main'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./sous-chef/sous_chef_unit_tests.xml,./sous-chef/sous_chef_integration_tests.xml
          fail_ci_if_error: true
          verbose: false
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: cov_sous_chef
          path: ./sous-chef/*.xml
          retention-days: 5
      - name: Run e2e tests
        if: github.ref == 'refs/heads/main'
        working-directory: ./sous-chef
        run: poetry run pytest -k "not dropbox and not openfoodfacts" ./tests/e2e_tests
