name: utilities tests
on:
  push:
    paths:
      - utilities/**
      - .github/workflows/test_utilities.yml
    branches-ignore:
      - main
  workflow_call:
    secrets:
      GSHEETS_SERVICE_TOKEN:
        required: true
      TODOIST_TOKEN:
        required: true
      CODECOV_TOKEN:
        required: true

concurrency:
  group: ${{ github.ref }}-utilities
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: ./.github/actions/poetry-setup-with-tokens
        with:
          poetry-dir: utilities
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
      - name: Run tests
        working-directory: ./utilities
        run: poetry run pytest --cov=utilities --cov-report=xml:utilities_tests.xml ./tests/
      - name: Upload coverage to Codecov
        if: github.ref != 'refs/heads/main'
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./utilities/utilities_tests.xml
          fail_ci_if_error: true
          verbose: false
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: cov_utilities
          path: ./utilities/*.xml
          retention-days: 5

