name: sous-chef tests
on:
  workflow_call:
    secrets:
      GSHEETS_SERVICE_TOKEN:
        required: true
      TODOIST_TOKEN:
        required: true
      SONAR_TOKEN_SOUS_CHEF:
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-sous-chef
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      relevant: ${{ steps.filter.outputs.relevant }}
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Check if relevant files were changed
        id: filter
        uses: ./.github/actions/check-file-changes
        with:
          paths: |
            sous-chef/
            utilities/utilities/
            .github/workflows/test_sous_chef.yml
  pytest:
    needs: changes
    if: needs.changes.outputs.relevant == 'true'
    runs-on: ubuntu-24.04
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v7
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python environment
        uses: ./.github/actions/poetry-setup-with-tokens
        with:
          poetry-dir: sous-chef
          poetry-lock-path: sous-chef/poetry.lock
          gsheets-service-token: ${{ secrets.GSHEETS_SERVICE_TOKEN }}
          todoist-token: ${{ secrets.TODOIST_TOKEN }}
      - name: Run unit tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_unit_tests.xml ./tests/unit_tests
      - name: Run integration tests
        working-directory: ./sous-chef
        run: poetry run pytest --cov=sous_chef --cov-report=xml:sous_chef_integration_tests.xml -k "not dropbox" ./tests/integration_tests
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@22918119ff8e1ca75a623e15c8296b6ea4fbe28f # v8.2.1
        with:
          projectBaseDir: ./sous-chef
          args: >-
            -Dsonar.projectKey=aurorianclouds.sous-chef
            -Dsonar.organization=aurorianclouds
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.sources=sous_chef
            -Dsonar.tests=tests
            -Dsonar.python.version=3.11,3.12,3.13,3.14
            -Dsonar.python.coverage.reportPaths=sous_chef_unit_tests.xml,sous_chef_integration_tests.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SOUS_CHEF }}
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7
        with:
          name: cov_sous_chef
          path: ./sous-chef/*.xml
          retention-days: 5
      - name: Run e2e tests
        working-directory: ./sous-chef
        run: poetry run pytest -k "not dropbox" ./tests/e2e_tests
