name: unit_test
on:
  push:
    paths:
      - sous-chef/**
      - .github/workflows/test_sous_chef.yml
env:
  PYTHON_VERSION: 3.9
  POETRY_VERSION: 1.2.2
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v2
      - name: Setup Python environment for sous-chef
        uses: ./.github/actions/sous-chef-setup
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          poetry-version: ${{ env.POETRY_VERSION }}
      - name: Run unit tests
        working-directory: ./sous-chef
        run: poetry run pytest ./tests/unit_tests
