name: banking-helpers tests
on:
  pull_request:
    paths:
      - banking-helpers/**
      - .github/workflows/test_banking_helpers.yml
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: true

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-banking-helpers
  cancel-in-progress: true

jobs:
  pytest:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out our repo branch
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up Python environment
        uses: ./.github/actions/poetry-setup
        with:
          poetry-dir: banking-helpers
      - name: Run unit tests
        working-directory: ./banking-helpers
        run: poetry run pytest --cov=banking_helpers --cov-report=xml:banking_helpers_unit_tests.xml ./tests/unit
      - name: Run integration tests
        working-directory: ./banking-helpers
        run: poetry run pytest --cov=banking_helpers --cov-report=xml:banking_helpers_integration_tests.xml ./tests/integration
      - name: Upload coverage to Codecov
        if: github.ref != 'refs/heads/main'
        uses: codecov/codecov-action@0fb7174895f61a3b6b78fc075e0cd60383518dac # v5.5.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./banking-helpers/banking_helpers_unit_tests.xml,./banking-helpers/banking_helpers_integration_tests.xml
          fail_ci_if_error: true
          verbose: false
      - name: Archive code coverage results
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v6
        with:
          name: cov_banking_helpers
          path: ./banking-helpers/*.xml
          retention-days: 5
